imports:
    - { resource: ../packages/doctrine_migrations.yaml }

output_data_config_toolkit:

    # possible values are [all, object, relevant, none]
    classification_store:
        display_mode: none

    # list of class names or ids
    tab_options:
        default_classes:
